In [1]:
import numpy as np

In [2]:
array = np.arange(1,13)
print(array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [3]:
array1 = array + 5
print(array1)

[ 6  7  8  9 10 11 12 13 14 15 16 17]


In [4]:
array2 = array * 2
print(array2)

[ 2  4  6  8 10 12 14 16 18 20 22 24]


In [5]:
print("Sum of the element:", np.sum(array))
print("Mean of the array:", np.mean(array))
print("Standard Deviation:", np.round(np.std(array),2))

Sum of the element: 78
Mean of the array: 6.5
Standard Deviation: 3.45


In [6]:
array_2d = array2.reshape(3,4)
print(array_2d)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [7]:
array3 = np.arange(1,26)
array4 = array3.reshape(5,5)
print(array4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [8]:
print(array4[1:4, 1:4])

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [9]:
a = np.arange(1,11)
b = np.arange(5,15)
a_2d = a.reshape(2,5)
b_2d = b.reshape(2,5)
print(a_2d)
print(b_2d,"\n")

c = a_2d + b_2d
print(c)
print(np.dot(a,b))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 5  6  7  8  9]
 [10 11 12 13 14]] 

[[ 6  8 10 12 14]
 [16 18 20 22 24]]
605


In [10]:
array = np.random.randint(1,20,10)
print(array)
print(np.sort(array))
print(np.sort(array)[:: -1])

[17 18 10 10  7  2  6  6  4 10]
[ 2  4  6  6  7 10 10 10 17 18]
[18 17 10 10 10  7  6  6  4  2]


In [11]:
a = np.arange(1,11)
b = np.arange(5,15)
a_2d = a.reshape(2,5)
b_2d = b.reshape(2,5)
print(a_2d)
print(b_2d,"\n")
print(a_2d == b_2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 5  6  7  8  9]
 [10 11 12 13 14]] 

[[False False False False False]
 [False False False False False]]


In [12]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
print([1,2,3] in array.tolist())
print([3,4,1] in array.tolist())

True
False


In [19]:
print(2 in array)
print(11 in array)

True
False


In [21]:
n_arr = np.array([[10.5, 22.5, 3.8],
                  [41, np.nan, np.nan]])
cleaned_array = n_arr[~np.isnan(n_arr).any(axis=1)]
cleaned_array

array([[10.5, 22.5,  3.8]])