# Python Data Handling with Pandas and NumPy

# 1. Python Programming Basics

In [13]:
# Function That Takes A List Of Numbers And Returns A New List With Each Number Squared
def square(lists):
    return list(map(lambda x: x**2, lists))
    
my_list = [1,2,3,4,5,6]
print("Square of the list is:",square(my_list))

Square of the list is: [1, 4, 9, 16, 25, 36]


In [14]:
# Function That Return Total Sum Of The List
def addition(lists):
    total = lambda x: sum(x)
    return total(lists)

my_list = [1,2,3,4,5,6]
print("Sum of the list:",addition(my_list))

Sum of the list: 21


In [18]:
# List Of 10 Integers, Use Function To Square These Numbers & Print Squared Lists.
def square(lists):
    return list(map(lambda x: x**2, lists))

my_list = []
for i in range(1,11):
    my_list.append(i)
print("Origianl List:",my_list)
print("Squared Lists: ",square(my_list))

Origianl List: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Squared Lists:  [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [92]:
# Create A Dictionary Where The Keys Are Names Of Students & The Values Are Their Scores In Exam.
my_dict = {
    "Alice": 85, "Bob": 92,
    "Charlie": 78, "David": 88,
    "Eve": 91, "Frank": 77,
    "Grace": 95, "Hannah": 82,
    "Ivy": 89,  "Kevin": 80,
}
print(my_dict)

{'Alice': 85, 'Bob': 92, 'Charlie': 78, 'David': 88, 'Eve': 91, 'Frank': 77, 'Grace': 95, 'Hannah': 82, 'Ivy': 89, 'Kevin': 80}


In [28]:
# Function That Takes Dictionary & Returns A New Dictionary With Only Those Students Who Scored Above 50
def above50(dicts):
    score = {name: sc for name, sc in dicts.items() if sc > 50}
    return score

my_dict = {
    "Alice": 85, "Bob": 45,
    "Charlie": 49, "David": 88,
    "Eve": 91, "Frank": 50,
    "Grace": 45, "Hannah": 82
}
print(above50(my_dict))

{'Alice': 85, 'David': 88, 'Eve': 91, 'Hannah': 82}


In [33]:
#Use Dictionary Comprehension To Create A Dictionary Where The Values Are Their Scores Multiplied By 1.1
def add_bonus(my_list):
    scores = {name: round(score * 1.1, 2) for name, score in my_dict.items()}
    return scores

my_dict = {
    "Alice": 85, "Bob": 45,
    "Charlie": 49, "David": 88,
    "Eve": 91, "Frank": 50,
    "Grace": 45, "Hannah": 82
}    
print(add_bonus(my_dict))

{'Alice': 93.5, 'Bob': 49.5, 'Charlie': 53.9, 'David': 96.8, 'Eve': 100.1, 'Frank': 55.0, 'Grace': 49.5, 'Hannah': 90.2}


# 2. Data Manipulation with Pandas

In [49]:
import pandas as pd
import numpy as np

In [54]:
# Create A DataFrame From This Dictionary.
data = {
'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
'Age': [25, 30, 35, 40, 45],
'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']
}
df = pd.DataFrame(data)
df

Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston
4      Eva   45      Phoenix

In [95]:
# Display The First Few Rows Of The DataFrame
print("First few of the dataFrame:")
df.head(3)

First few of the dataFrame:


Name  Age         City AgeGroup
0    Alice   25     New York    Adult
1      Bob   30  Los Angeles    Adult
2  Charlie   35      Chicago    Adult

In [52]:
# Calculate & Print The Average Age From The DataFrame.
print("Average Age Of The Student:",np.average(df['Age']))

Average Age Of The Student: 35.0


In [53]:
# Filter The DataFrame To Include Only Rows Where The Age Is Greater Than 30.
filter_df = df[df['Age']> 30]
filter_df

Name  Age     City
2  Charlie   35  Chicago
3    David   40  Houston
4      Eva   45  Phoenix

In [57]:
# Add A New Column To The DataFrame Called AgeGroup.
df['AgeGroup'] = df['Age'].apply(lambda x: "Seniors" if x>=40 else "Adult")
df

Name  Age         City AgeGroup
0    Alice   25     New York    Adult
1      Bob   30  Los Angeles    Adult
2  Charlie   35      Chicago    Adult
3    David   40      Houston  Seniors
4      Eva   45      Phoenix  Seniors

In [66]:
# Group The Data By AgeGroup & Calculate The Average Age For Each Group.
gp = df.groupby('AgeGroup')['Age'].mean()
print(gp)

AgeGroup
Adult      30.0
Seniors    42.5
Name: Age, dtype: float64


# 3. Data Manipulation with NumPy

In [70]:
# Create A NumPy Array With 12 Random Integers Between 1 & 50.
array = np.random.randint(1,50,size=12)
print("The NumPy Array Is:",array)

The NumPy Array Is: [36 34  1 19 18 16 15 14 39 48 21 13]


In [79]:
# Reshape The Array Into A 3x4 Matrix.
print("1D Array is:",array, "\n")
array_2d = array.reshape(3,4)
print("2D Array is:")
print(array_2d)

1D Array is: [36 34  1 19 18 16 15 14 39 48 21 13] 

2D Array is:
[[36 34  1 19]
 [18 16 15 14]
 [39 48 21 13]]


In [85]:
# Find & Print The Maximum, Minimum, & Mean Values Of The Array.
print("Maximum element in the array:", np.max(array))
print("Minimum element in the array:", np.min(array))
print("Mean of the array:", round(np.mean(array),2))

Maximum element in the array: 48
Minimum element in the array: 1
Mean of the array: 22.83


In [87]:
# Create A NumPy Array Of Shape (4, 3) With Values From 1 To 12
array_2d = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(array_2d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [91]:
# Extract & Print The Second Row Of The Array.
print("The Second Row Of The Array:",array_2d[1,:])

The Second Row Of The Array: [4 5 6]


In [90]:
# Extract & Print A 2x2 Submatrix from the top-left corner of the array.
print("Extracted 2x2 Submatrix:")
print(array_2d[:2,:2])

Extracted 2x2 Submatrix:
[[1 2]
 [4 5]]
